export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR';

export const PRODUCTS_FETCH = 'PRODUCTS_FETCH';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_ERROR = 'PRODUCTS_FETCH_ERROR';

export const CATEGORIES_FETCH = 'CATEGORIES_FETCH';
export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS';
export const CATEGORIES_FETCH_ERROR = 'CATEGORIES_FETCH_ERROR';

export const PRODUCT_EDIT = 'PRODUCT_EDIT';
export const PRODUCT_EDIT_CLOSE = 'PRODUCT_EDIT_CLOSE';
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_ERROR = 'PRODUCT_EDIT_ERROR';
export const PRODUCT_EDIT_START = 'PRODUCT_EDIT_START';

export const CART_EDIT = 'CART_EDIT';
export const CART_SEND_START = 'CART_SEND_START';
export const CART_SEND_SUCCESS = 'CART_SEND_SUCCESS';
export const CART_SEND_ERROR = 'CART_SEND_ERROR';
export const CART_POPULAR_ITEMS_EDIT = 'CART_POPULAR_ITEMS_EDIT';

export const SEARCH_EDIT = 'SEARCH_EDIT'